var Client = require('ftp');
var googleAuth = require('./google-apis.js');
var fs = require('fs');
var recursiveCheck = require('./utils.js').recursiveCheck;

var SiteMap = function(url, list) {
	this.url = url;
	this.list = list;
	this.build();
	return this;
};
SiteMap.prototype.build = function() {
	console.log('list: ', this.list);
	var siteMap = ['<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n\n<!-- Generated by: Site Monitor.. -->\n\n'];
	this.list.forEach(function(obj) {
		// console.log('fileType: ', obj.fileType);
		if( this._isHtml(obj.fileType) || this._isPdf(obj.fileType) ) {
			if( obj.lastModified !== null ) {
				siteMap.push('\n<url>\n\t<loc>'+obj.fileName+'</loc>\n\t<lastmod>'+obj.lastModified+'</lastmod>\n</url>');
			}
			else {
				siteMap.push('\n<url>\n\t<loc>'+obj.fileName+'</loc>\n</url>');
			}
		}
	}.bind(this));
	siteMap.push('\n\n</urlset>');
	this.siteMap = siteMap;
	this.saveLocal();
	return this;
};
SiteMap.prototype._isHtml = function(fileType) { return /text\/html/.test(fileType) };
SiteMap.prototype._isPdf = function(fileType) { return /application\/pdf/.test(fileType) };
SiteMap.prototype.submitedToGoogle = 0;
SiteMap.prototype.ftped = 0;
SiteMap.prototype.saveLocal  = function() {
	var string = this.siteMap.join('');
	fs.unlink('sitemap.xml', function() {
    	console.log('deleted');
    	fs.appendFile('siteMap.xml', string, 'utf8', function() {
	    	console.log('done');
	    });
    });
};
SiteMap.prototype.checkReady = function() {
	console.log('checkReady');
	recursiveCheck(
		'ftp-google-ready', 

		/* is ready check.. */
		this._ftpAndGoogleReadyCheck.bind(this),

		/* on ready callback.. */
		this._ftpAndGoogleReady.bind(this)
	);
};
SiteMap.prototype._ftpAndGoogleReadyCheck = function() {
	return this.ftped === -1 || ( this.ftped != 0 && this.submitedToGoogle != 0 ) ? true : false;
};
SiteMap.prototype._ftpAndGoogleReady = function() {
	if(this.ftped === -1) this._submitCallback('ftpError');
	else if( this.ftped === 1 && this.submitedToGoogle === 1 ) this._submitCallback('pendingGoogleSiteConfirm');
	else if( this.ftped === 1 && this.submitedToGoogle === 2 ) this._submitCallback('siteMapSubmited');
};
SiteMap.prototype.submit = function(config, callback, errback) {
	console.log('submit');
	this._submitCallback = callback;
	this._submitErrback = errback;
	this.checkReady();
	this._ftp({}, function() {
		console.log('fpt done: ', this.ftped);
		if(this.ftped === -1) return;
		this._submitToGoogle();
	}.bind(this));
};
SiteMap.prototype._submitCallback = function(message) {};
SiteMap.prototype._submitErrback = function(message) {};
SiteMap.prototype._submitToGoogle = function() {
	console.log('submit to google');
	googleAuth.submitSiteMap(this.url, this.url+'/siteMap.xml', 
		this._submitToGoogleComplete.bind(this),
		this._submitToGoogleError.bind(this)
	);
};
SiteMap.prototype._submitToGoogleComplete = function(o) {
	console.log('submitedToGoogleComplete: ', o);
	this.submitedToGoogle = 2;
};
SiteMap.prototype._submitToGoogleError = function(o) {
	console.log('submitedToGoogleError', o);
	this.submitedToGoogle = -1;
};
SiteMap.prototype._ftp = function(connect, callback) {

	var c = new Client();

	c.on('greeting', function(msg) { console.log('greeting', msg); });
	// c.on('close', function() { console.log('close'); });
	// c.on('end', function() { console.log('end'); });
	c.on('error', function(err) { 
		this.ftped = -1;
		console.log('error', err); 
	}.bind(this)); 

	c.on('ready', function() {
        c.put('/portfolio/siteMap.xml', 'siteMap.xml', function(err) {

            if (err) {
            	this.ftped = -1;
            	callback(err);
            	return;
            }
            this.ftped = 1;
            c.end();
            callback();

        }.bind(this));
	}.bind(this));

	c.connect({
	    host:  process.env.HOST,
	    user: process.env.USER,
	    password: process.env.PASS,
	});
	// c.connect(connect);
};

module.exports = SiteMap;